set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

# Point to your MounRiver or riscv-none-elf toolchain
set(TOOLCHAIN_PREFIX "riscv-none-embed-")

# Adjust this path to where you installed the toolchain
set(TOOLCHAIN_PATH "$ENV{CH32_TOOLCHAIN_DIR}/bin")

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}gcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}g++.exe")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}gcc.exe")
set(CMAKE_OBJCOPY      "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}objcopy.exe")
set(CMAKE_SIZE         "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}size.exe")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)